apiVersion: v1
kind: Secret
metadata:
  name: repo-myprivate
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/TracVietHustCS/eks-nemi-gitops.git
  username: TracVietHustCS
  password: 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
